### ISSUE TITLE
`konf delete` option so you can delete konfs you don't need anymore

### ISSUE THREAD

**Issue by almereyda** [SimonTheLeg/konf-go#32]
Taken from README.md

**Comment by almereyda** [comment]
This will be very useful when working with ephemeral clusters a lot.

Also manual instructions on how to remove a context from `konf` are highly appreciated.

**Comment by SimonTheLeg** [comment]
Yes that is a good point. I am currently working on this feature. Hopefully it will be ready in a couple of days.

---
> Meanwhile manual instructions on how to remove a context from konf are highly appreciated.

For now you can directly remove the file from the store, which is by default located at ` ~/.kube/konfs/store/<context-name>_<cluster-name>`. 
This will directly remove the file from the selection-prompt.

**Comment by almereyda** [comment]
Many thanks!

**Comment by SimonTheLeg** [comment]
delete is now merged and available in konf v0.2.0
