### ISSUE TITLE
version command is missing

### ISSUE THREAD

**Issue by superherointj** [SimonTheLeg/konf-go#38]
version command is missing

Asking to fix package version at Nixpkgs.

**Comment by SimonTheLeg** [comment]
@superherointj 
From my understanding you want a `konf version` command. Regarding the output of the command:

1. Is there a particular output format you would like to see? I have seen that most Go apps use json
2. What particular information would you want to see? GitTag, GitCommit, Platform? Anything else?

**Comment by superherointj** [comment]
> @superherointj From my understanding you want a `konf version` command.

Yes! :)

> Regarding the output of the command:
> 
>     1. Is there a particular output format you would like to see? I have seen that most Go apps use json

I just need it to output the version anywhere. json or not. Whatever is easier for you is fine.

>     2. What particular information would you want to see? GitTag, GitCommit, Platform? Anything else?

It is only important the version for me. These other informations are optional.
