### ISSUE TITLE
Import kubeconfigs under a directory 

### ISSUE THREAD

**Issue by rumstead** [SimonTheLeg/konf-go#43]
Be able to import all kube configs under a directory

**Comment by SimonTheLeg** [comment]
That is a good idea. 

I think, I will implement it similar to the current `konf delete`, which allows a file glob to match multiple files. An then something like `konf import .` or `konf import /path/to/my/dir` will be possible

**Comment by SimonTheLeg** [comment]
okay this should work now. When you supply a directory to `konf import`, it will import all files in that directory (excl. hidden ones of course)
